server:
  port: 8082
  
spring:
  cloud:
    gateway:
      routes:
      - id: welcomeGateway
        uri: http://localhost:8081
        predicates:
        - Path=/welcome/client/**
  application:
    name: gateaway
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
        


eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost